github.com:
    users:
        hsigrist:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: hsigrist
